/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectf;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author rpmulligan
 */
public class lineup extends javax.swing.JFrame {

    /**
     * Creates new form Lineup
     */
    public lineup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        team_label = new javax.swing.JLabel();
        team_textfield = new javax.swing.JTextField();
        home_radio = new javax.swing.JRadioButton();
        visitor_radio = new javax.swing.JRadioButton();
        Player_label_1 = new javax.swing.JLabel();
        player_1_textfield = new javax.swing.JTextField();
        choice_player_1 = new java.awt.Choice();
        Player_label_2 = new javax.swing.JLabel();
        player_2_textfield = new javax.swing.JTextField();
        choice_player_3 = new java.awt.Choice();
        Player_label_3 = new javax.swing.JLabel();
        player_3_textfield = new javax.swing.JTextField();
        choice_player_2 = new java.awt.Choice();
        Player_label_4 = new javax.swing.JLabel();
        player_4_textfield = new javax.swing.JTextField();
        choice_player_4 = new java.awt.Choice();
        Player_label_5 = new javax.swing.JLabel();
        player_6_textfield = new javax.swing.JTextField();
        choice_player_5 = new java.awt.Choice();
        Player_label_6 = new javax.swing.JLabel();
        player_5_textfield = new javax.swing.JTextField();
        choice_player_7 = new java.awt.Choice();
        Player_label_7 = new javax.swing.JLabel();
        player_7_textfield = new javax.swing.JTextField();
        choice_player_6 = new java.awt.Choice();
        Player_label_8 = new javax.swing.JLabel();
        player_8_textfield = new javax.swing.JTextField();
        choice_player_9 = new java.awt.Choice();
        Player_label_9 = new javax.swing.JLabel();
        player_9_textfield = new javax.swing.JTextField();
        choice_player_8 = new java.awt.Choice();
        exit_button = new javax.swing.JButton();
        okay_button = new javax.swing.JButton();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lineup");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Team Information"));

        team_label.setText("Team Name:");

        team_textfield.setText("Team Name");
        team_textfield.setToolTipText("");
        team_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team_textfieldActionPerformed(evt);
            }
        });

        home_radio.setText("Home");
        home_radio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                home_radioInputMethodTextChanged(evt);
            }
        });
        home_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_radioActionPerformed(evt);
            }
        });

        visitor_radio.setText("Visitor");
        visitor_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                visitor_radioItemStateChanged(evt);
            }
        });

        
        
        home_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                home_radioItemStateChanged(evt);
            }
        });

        
        
        
        visitor_radio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                visitor_radioInputMethodTextChanged(evt);
            }
        });

        home_radio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                home_radioInputMethodTextChanged(evt);
            }
        });
       


        visitor_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitor_radioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(team_label)
                .addGap(18, 18, 18)
                .addComponent(team_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(home_radio)
                .addGap(18, 18, 18)
                .addComponent(visitor_radio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team_label)
                    .addComponent(team_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_radio)
                    .addComponent(visitor_radio))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Player_label_1.setText("1:");

        player_1_textfield.setText("Player Name");
        player_1_textfield.setToolTipText("");
        player_1_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_1_textfieldActionPerformed(evt);
            }
        });

        Player_label_2.setText("2:");

        player_2_textfield.setText("Player Name");
        player_2_textfield.setToolTipText("");
        player_2_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_2_textfieldActionPerformed(evt);
            }
        });

        Player_label_3.setText("3:");

        player_3_textfield.setText("Player Name");
        player_3_textfield.setToolTipText("");
        player_3_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_3_textfieldActionPerformed(evt);
            }
        });

        Player_label_4.setText("4:");

        player_4_textfield.setText("Player Name");
        player_4_textfield.setToolTipText("");
        player_4_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_4_textfieldActionPerformed(evt);
            }
        });

        Player_label_5.setText("5:");
        Player_label_5.setToolTipText("");

        player_6_textfield.setText("Player Name");
        player_6_textfield.setToolTipText("");
        player_6_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_6_textfieldActionPerformed(evt);
            }
        });

        Player_label_6.setText("6:");
        Player_label_6.setToolTipText("");

        player_5_textfield.setText("Player Name");
        player_5_textfield.setToolTipText("");
        player_5_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_5_textfieldActionPerformed(evt);
            }
        });

        Player_label_7.setText("7:");
        Player_label_7.setToolTipText("");

        player_7_textfield.setText("Player Name");
        player_7_textfield.setToolTipText("");
        player_7_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_7_textfieldActionPerformed(evt);
            }
        });

        Player_label_8.setText("8:");
        Player_label_8.setToolTipText("");

        player_8_textfield.setText("Player Name");
        player_8_textfield.setToolTipText("");
        player_8_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_8_textfieldActionPerformed(evt);
            }
        });

        Player_label_9.setText("9:");
        Player_label_9.setToolTipText("");

        player_9_textfield.setText("Player Name");
        player_9_textfield.setToolTipText("");
        player_9_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_9_textfieldActionPerformed(evt);
            }
        });

        
        exit_button.setText("Exit");
        okay_button.setText("Okay");

        
        
        int i = 0; 
        String [] positions = {"Center Field", "Left Field", "Right Field",
                    "First Base", "Second Base", "Third Base", "Short Stop",
                    };
        for(i = 0; i < positions.length; i++) {
            choice_player_1.addItem(positions[i]);
            choice_player_2.addItem(positions[i]);            
            choice_player_3.addItem(positions[i]);
            choice_player_4.addItem(positions[i]);
            choice_player_5.addItem(positions[i]);
            choice_player_6.addItem(positions[i]);            
            choice_player_7.addItem(positions[i]);
            choice_player_8.addItem(positions[i]);
            choice_player_9.addItem(positions[i]);
        }
        
        JButton btnOkay = new JButton("Okay");
        btnOkay.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		
        		String name = team_textfield.getText();        		
        		System.out.println(name);
        		
                System.out.println(player_1_textfield.getText() + " " + choice_player_1.getSelectedItem()  );
                System.out.println(player_2_textfield.getText() + " " + choice_player_2.getSelectedItem()  );
                System.out.println(player_3_textfield.getText() + " " + choice_player_3.getSelectedItem()  );
                System.out.println(player_4_textfield.getText() + " " + choice_player_4.getSelectedItem()  );
                System.out.println(player_5_textfield.getText() + " " + choice_player_5.getSelectedItem()  );
                System.out.println(player_6_textfield.getText() + " " + choice_player_6.getSelectedItem()  );
                System.out.println(player_7_textfield.getText() + " " + choice_player_7.getSelectedItem()  );
                System.out.println(player_8_textfield.getText() + " " + choice_player_8.getSelectedItem()  );
                System.out.println(player_9_textfield.getText() + " " + choice_player_9.getSelectedItem()  );
        	
        	}
        });
        
        JButton btnExit = new JButton("Exit");
        btnExit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	System.exit(0);
        	}
        });
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(81)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_9)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_9_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_8)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_8_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_7)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_7_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_6)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_6_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_5)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_5_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_4)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_4_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_3)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(player_3_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_2)
        									.addGap(46)
        									.addComponent(player_2_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(Player_label_1)
        									.addGap(46)
        									.addComponent(player_1_textfield, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)))
        							.addGap(102)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(choice_player_1, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_3, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_2, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_4, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_5, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_7, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_6, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_9, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(choice_player_8, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        								.addComponent(btnExit, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(313)
        					.addComponent(btnOkay, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(46)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(choice_player_5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(22))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(choice_player_4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(34)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        									.addComponent(Player_label_1)
        									.addComponent(player_1_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        								.addComponent(choice_player_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(Player_label_2)
        									.addComponent(player_2_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        								.addComponent(choice_player_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(Player_label_3)
        									.addComponent(player_3_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        								.addComponent(choice_player_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(Player_label_4)
        								.addComponent(player_4_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        					.addPreferredGap(ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(Player_label_5)
        							.addGap(6))
        						.addComponent(player_5_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(Player_label_6)
        						.addComponent(player_6_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(Player_label_7)
        						.addComponent(player_7_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(choice_player_6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(choice_player_7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(choice_player_8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(Player_label_8)
        					.addComponent(player_8_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(Player_label_9)
        					.addComponent(player_9_textfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(choice_player_9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnOkay)
        				.addComponent(btnExit))
        			.addGap(33))
        );
        getContentPane().setLayout(layout);
                

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_radioActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_home_radioActionPerformed

    private void visitor_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitor_radioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_visitor_radioActionPerformed

    private void player_1_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_1_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_1_textfieldActionPerformed

    private void team_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team_textfieldActionPerformed

    private void player_2_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_2_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_2_textfieldActionPerformed

    private void player_3_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_3_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_3_textfieldActionPerformed

    private void player_4_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_4_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_4_textfieldActionPerformed

    private void player_6_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_6_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_6_textfieldActionPerformed

    private void player_5_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_5_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_5_textfieldActionPerformed

    private void player_7_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_7_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_7_textfieldActionPerformed

    private void player_8_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_8_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_8_textfieldActionPerformed

    private void player_9_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_9_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player_9_textfieldActionPerformed

    private void home_radioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_home_radioInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_home_radioInputMethodTextChanged

    private void visitor_radioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_visitor_radioInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_visitor_radioInputMethodTextChanged

    private void visitor_radioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_visitor_radioItemStateChanged
        // TODO add your handling code here:
      if(evt.getStateChange() == evt.SELECTED){
        home_radio.setSelected(false);    
      }

    }//GEN-LAST:event_visitor_radioItemStateChanged

    private void home_radioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_visitor_radioItemStateChanged
        // TODO add your handling code here:
      if(evt.getStateChange() == evt.SELECTED){
        visitor_radio.setSelected(false);    
      }

    }//GEN-LAST:event_visitor_radioItemStateChanged



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lineup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lineup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lineup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lineup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lineup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Player_label_1;
    private javax.swing.JLabel Player_label_2;
    private javax.swing.JLabel Player_label_3;
    private javax.swing.JLabel Player_label_4;
    private javax.swing.JLabel Player_label_5;
    private javax.swing.JLabel Player_label_6;
    private javax.swing.JLabel Player_label_7;
    private javax.swing.JLabel Player_label_8;
    private javax.swing.JLabel Player_label_9;
    private java.awt.Choice choice_player_1;
    private java.awt.Choice choice_player_2;
    private java.awt.Choice choice_player_3;
    private java.awt.Choice choice_player_4;
    private java.awt.Choice choice_player_5;
    private java.awt.Choice choice_player_6;
    private java.awt.Choice choice_player_7;
    private java.awt.Choice choice_player_8;
    private java.awt.Choice choice_player_9;
    private javax.swing.JRadioButton home_radio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField player_1_textfield;
    private javax.swing.JTextField player_2_textfield;
    private javax.swing.JTextField player_3_textfield;
    private javax.swing.JTextField player_4_textfield;
    private javax.swing.JTextField player_5_textfield;
    private javax.swing.JTextField player_6_textfield;
    private javax.swing.JTextField player_7_textfield;
    private javax.swing.JTextField player_8_textfield;
    private javax.swing.JTextField player_9_textfield;
    private javax.swing.JLabel team_label;
    private javax.swing.JTextField team_textfield;
    private javax.swing.JRadioButton visitor_radio;

    private javax.swing.JButton exit_button;
    private javax.swing.JButton okay_button;    
}
